string name
int32 id
int8 location
int8 box_placement_location_code
geometry_msgs/PoseStamped pose
#bool use_wrist_far


# location list
int8 UNASSIGNED=0 # unconfirmed location

int8 QUALITY_SENSOR_1=51
int8 QUALITY_SENSOR_2=52

int8 BIN1=1
int8 BIN2=2
int8 BIN3=3
int8 BIN4=4
int8 BIN5=5
int8 BIN6=6
int8 BIN7=7
int8 BIN8=8
int8 BIN9=9
int8 BIN10=10
int8 BIN11=11
int8 BIN12=12

int8 DISCARD_Q1=21
int8 DISCARD_Q2=21
